### PR TITLE
JENKINS-17297 Plugin hipchat: Not working when sendAs is empty

### PR DESCRIPTION
**Pull request by phil-schneider**
- I removed the setting methods (not needed and only set via the constructor)
- fixed the bug (see jira)
- problem was that the String is not null but empty. This returns a bad request from the hipchat API. Replaced check for null with Stringutils.

### CODE REVIEW

**Comment by kellybyrd** [comment]
There's a ton of stuff in this pull request now, probably because it wasn't done on a feature branch. I'm testing out just 556d931 locally to see if it does what it says on the tin (I think it will). It would be really helpful if you could put just that commit on it's own branch, create a pull request for it from that new branch, and close this pull request. 

If not, when I get around to it, I'll guess I'll do this myself.

**Comment by chrisklaiber** [comment]
@kellybyrd fwiw, the `StringUtils.isBlank()` fix is also part of #40 (and will likely conflict).

**Comment by kellybyrd** [comment]
Uggg. We'll I just tested that locally and it latest on this repo wouldn't work without it for us. I'm not willing to merge #40 without at least looking at it (because I'm new here) but it's probably better for everyone if I merge 556d931  ASAP. I'll do that now and have a look at #40 today or tonight. If I could get input from the other maintainers (new or old) or if they want to tackle it, that would be great.

**Comment by kellybyrd** [comment]
nevermind. I cherry-picked just 556d931. In the future, please do pull requests on feature branches by themselves and then merge them back to your own master if you want to develop on top of them.

**Pull request closed without merging**
